import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "./ConvexClientProvider";

// Keep JetBrains for your code blocks (available via "font-mono" in your components)
const jetbrainsMono = JetBrains_Mono({ subsets: ['latin'], variable: '--font-mono' });

// Set Geist Sans as your default sans-serif font
const geistSans = Geist({
  variable: "--font-sans", // Changed this to --font-sans for Tailwind compatibility
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TripMate - Your Travel Companion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        suppressHydrationWarning
        // Replaced "font-mono" with "font-sans" so Geist is the default text
        className={cn("h-full", "antialiased", geistSans.variable, jetbrainsMono.variable, "font-sans")}
      >
        <body className="min-h-full flex flex-col">


          <ConvexClientProvider>
            {children}
          </ConvexClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}